### ISSUE TITLE
[Feature]: adapt ScribbleLab for iPhone

### ISSUE THREAD

**Issue by N3v1** [ScribbleLabApp/ScribbleLab#54]
### Description

Hey fellow contributor/staff member,
We want to inform you that ScribbleLab is currently not optimized for iPhone. As a valued contributor, would you be able to assist us in adapting the platform for iPhone users? Your expertise and contributions would be greatly appreciated! Thank you for your time.

## ToDo's

- [ ] Adapt Auth UI to iPhone
- [ ] Adapt HomeView to iPhone
- [ ] Only for iPhone: TabBar instead of SideBar
- [x] Adapt Settings to iPhone
- [x] Adapt Launch Screen to iPhone

### Alternatives Considered

Instead of a SideBar use a TabBar

### Additional Context

Join our [community](https://discord.gg/Y9SmAGfJMR) to make collaboration as easy as possible.

### Screenshots

| SignUpView | SignInView | SideBarView | TutorialView | NewsView |
|--------|--------|--------|--------|--------|
| ![SignUpView](https://github.com/ScribbleLabApp/ScribbleLab/assets/129311622/25ccaf37-fc1b-4dcc-9c84-4f0e9a0225c8) | ![SignInView](https://github.com/ScribbleLabApp/ScribbleLab/assets/129311622/42024f70-1754-418d-bc30-55934d951179) | ![SideBarView](https://github.com/ScribbleLabApp/ScribbleLab/assets/129311622/96057c99-0099-4aec-84f2-d9b1bf090cec) | ![5283997D-4052-46AD-A169-3EE455D93FEC_1_102_o](https://github.com/ScribbleLabApp/ScribbleLab/assets/129311622/fa9543de-01cc-47bd-a08a-4f4614bf4675)
 | ![6A05D390-6FF7-4A6F-9F22-12EBA43178A1_1_102_o](https://github.com/ScribbleLabApp/ScribbleLab/assets/129311622/0f41e21c-6fb7-4c46-8401-524e5e432c3e) |

### Is there an existing issue for this?

- [X] I have searched the existing issues
